#pragma once

#define FIELD_SIZE            8
#define LED_INTENSITY_MEDIUM  8
#define START_LENGTH          2
#define START_ROW             4
#define START_COLUMN          4
#define DELAY_GENERAL         400
#define DELAY_LETTER          100
#define DELAY_GAMEOVER        800
#define SENSIVITY_LEFT        700
#define SENSIVITY_RIGHT       300
#define SENSIVITY_DOWN        600
#define SENSIVITY_UP          400
#define NOT_EMPTY             -1
#define STR_GAMEOVER_LENGTH   80
#define STR_STARTGAME_LENGTH  43
#define LIMIT_X_HIGH          600
#define LIMIT_X_LOW           400
#define LIMIT_Y_HIGH          600
#define LIMIT_Y_LOW           400
#define TONE_PIN              4
#define TONE_MINLEVEL         3000
#define TONE_GAP              100
#define TONE_DURATION         100
#define TONE_CORRECTION       20
#define CONTROL_PORT_X        1
#define CONTROL_PORT_Y        0
#define CONTROL_XCORRECTION   -507
#define CONTROL_YCORRECTION   -507
#define CONTROL_NEUTRALZONE   50
